# -*- coding: utf-8 -*-
"""DashBoard_Global-clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1af3SeBGBQPngvKNlq851Wi_tektdFErY
"""

# Global Development Clustering Dashboard

import streamlit as st
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import plotly.express as px

file_path = r"C:/Users/venka/Downloads/cleaned_Global_clustering.csv"
df_raw = pd.read_csv(file_path)

avg_countries = df_raw.groupby("Country").mean().reset_index()

numeric_cols = avg_countries.select_dtypes(include='number').columns
scaler = StandardScaler()
avg_countries[numeric_cols] = scaler.fit_transform(avg_countries[numeric_cols])

kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
avg_countries["Cluster"] = kmeans.fit_predict(avg_countries[numeric_cols])

positive_features = [
    "GDP", "Life Expectancy Female", "Life Expectancy Male",
    "Internet Usage", "Mobile Phone Usage",
    "Health Exp % GDP", "Health Exp/Capita", "Tourism Inbound"
]

negative_features = [
    "Infant Mortality Rate", "Birth Rate", "Lending Interest", "Tourism Outbound"
]

avg_countries[negative_features] = avg_countries[negative_features] * -1

check = avg_countries.groupby("Cluster")[positive_features + negative_features].mean()
check["Score"] = check.sum(axis=1)

ordered_clusters = check.sort_values("Score").index.tolist()
cluster_map = {
    ordered_clusters[0]: "Rising Nations",
    ordered_clusters[1]: "Advanced Nations",
    ordered_clusters[2]: "Global Leaders"
}

avg_countries["Development_Tier"] = avg_countries["Cluster"].map(cluster_map)

df = avg_countries

fig = px.scatter(
    df,
    x="GDP",
    y="Life Expectancy Female",
    color="Development_Tier",
    hover_name="Country",
    title="Country Development Clusters (All Features)",
    color_discrete_map={
        "Global Leaders": "green",
        "Advanced Nations": "royalblue",
        "Rising Nations": "orange"
    }
)
st.plotly_chart(fig)

# Development tier mapping

check = avg_countries.groupby("Cluster")[numeric_cols].mean()
check["Score"] = check.sum(axis=1)

ordered_clusters = check.sort_values("Score").index.tolist()
cluster_map = {
    ordered_clusters[0]: "Rising Nations",
    ordered_clusters[1]: "Advanced Nations",
    ordered_clusters[2]: "Global Leaders"
}

df["Development_Tier"] = df["Cluster"].map(cluster_map)

# Sidebar controls for dashboard navigation

st.sidebar.title("Dashboard Controls")

view = st.sidebar.radio("Select View", ["World Overview", "Country Explorer"])

country = None

if view == "Country Explorer":
    country = st.sidebar.selectbox("Select Country", sorted(df["Country"].unique()))

# World overview visualizations

if view == "World Overview":
    st.title("World Overview")

    fig_map = px.choropleth(
        df,
        locations="Country",
        locationmode="country names",
        color="Development_Tier",
        hover_name="Country",
        hover_data=[
            "GDP", "Life Expectancy Female", "Life Expectancy Male",
            "Infant Mortality Rate", "Internet Usage", "Birth Rate",
            "Health Exp % GDP", "Health Exp/Capita", "Mobile Phone Usage",
            "Lending Interest", "Tourism Inbound", "Tourism Outbound"
        ],
        color_discrete_map={
            "Global Leaders": "green",
            "Advanced Nations": "royalblue",
            "Rising Nations": "orange"
        }
    )
    st.plotly_chart(fig_map, use_container_width=True)

    x_axis = st.selectbox("Select X-axis feature", numeric_cols, index=numeric_cols.get_loc("Birth Rate"))
    y_axis = st.selectbox("Select Y-axis feature", numeric_cols, index=numeric_cols.get_loc("Life Expectancy Female"))

    fig_scatter = px.scatter(
        df,
        x=x_axis,
        y=y_axis,
        color="Development_Tier",
        hover_name="Country",
        color_discrete_map={
            "Global Leaders": "green",
            "Advanced Nations": "royalblue",
            "Rising Nations": "orange"
        }
    )
    st.plotly_chart(fig_scatter, use_container_width=True)

    cluster_counts = df["Development_Tier"].value_counts().reset_index()
    cluster_counts.columns = ["Development_Tier", "Count"]
    fig_bar = px.bar(
        cluster_counts,
        x="Development_Tier",
        y="Count",
        color="Development_Tier",
        text="Count",
        color_discrete_map={
            "Global Leaders": "green",
            "Advanced Nations": "royalblue",
            "Rising Nations": "orange"
        }
    )
    fig_bar.update_traces(textposition="outside")
    st.plotly_chart(fig_bar, use_container_width=True)

# Country explorer view

if view == "Country Explorer" and country:
    st.title(f"Country Explorer: {country}")
    country_data = df[df["Country"] == country].iloc[0]

    st.metric("Development Tier", country_data["Development_Tier"])
    st.metric("GDP", f"{country_data['GDP']:.2f}")
    st.metric("Life Expectancy (Female)", f"{country_data['Life Expectancy Female']:.2f}")
    st.metric("Life Expectancy (Male)", f"{country_data['Life Expectancy Male']:.2f}")
    st.metric("Infant Mortality Rate", f"{country_data['Infant Mortality Rate']:.2f}")
    st.metric("Birth Rate", f"{country_data['Birth Rate']:.2f}")
    st.metric("Internet Usage", f"{country_data['Internet Usage']:.2f}")
    st.metric("Mobile Phone Usage", f"{country_data['Mobile Phone Usage']:.2f}")
    st.metric("Health Exp % GDP", f"{country_data['Health Exp % GDP']:.2f}")
    st.metric("Health Exp/Capita", f"{country_data['Health Exp/Capita']:.2f}")
    st.metric("Lending Interest", f"{country_data['Lending Interest']:.2f}")
    st.metric("Tourism Inbound", f"{country_data['Tourism Inbound']:.2f}")
    st.metric("Tourism Outbound", f"{country_data['Tourism Outbound']:.2f}")

    st.write(
        f"This country is classified as **{country_data['Development_Tier']}**, "
        f"based on a composite of economic, health, and social indicators. "
        f"Strong GDP and life expectancy support advancement, while "
        f"factors like infant mortality, birth rate, and lending interest "
        f"can challenge progress within the tier."
    )

# Histogram and methodology view

if view == "Country Explorer" and country:
    features = [col for col in df.columns if col not in ["Country","Cluster","Development_Tier"]]
    country_data = df[df["Country"] == country].iloc[0]
    feature_values = country_data[features]

    fig_hist = px.bar(
        x=features,
        y=feature_values,
        labels={"x":"Features","y":"Standardized Value"},
        title=f"{country} Profile (All Features)"
    )
    st.plotly_chart(fig_hist, use_container_width=True)

    with st.expander("Methodology"):
        st.write("""
        - Data aggregated to one row per country.
        - Features standardized using StandardScaler.
        - Negative indicators (Infant Mortality, Birth Rate, Lending Interest, Tourism Outbound) flipped so higher = better.
        - KMeans clustering with 3 clusters.
        - Clusters mapped to Rising Nations / Advanced Nations / Global Leaders tiers.
        """)

    global_means = df[features].mean()
    comparison = pd.DataFrame({
        "Feature": features,
        "Country": feature_values.values,
        "Global Average": global_means.values
    })
    comparison_long = comparison.melt(
        id_vars="Feature",
        value_vars=["Country","Global Average"],
        var_name="Source",
        value_name="Value"
    )

    fig_compare = px.bar(
        comparison_long,
        x="Feature",
        y="Value",
        color="Source",
        barmode="group",
        title=f"{country} vs Global Average"
    )
    st.plotly_chart(fig_compare, use_container_width=True)